development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:5536e3aafe8e7f689ebd5e409f5d2191@hammerjaw.redistogo.com:10022/
  channel_prefix: tic_tac_toe_rails_react_production
